[app_servers]
app1 ansible_host=18.212.130.60 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/final-project-key.pem
app2 ansible_host=204.236.251.162 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/final-project-key.pem

[db_servers]
db ansible_host=34.230.55.127 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/final-project-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3