[app_servers]
app1 ansible_host=54.89.236.238 ansible_user=ubuntu ansible_ssh_private_key_file=../final-project-key.pem
app2 ansible_host=13.217.108.233 ansible_user=ubuntu ansible_ssh_private_key_file=../final-project-key.pem

[db_servers]
db ansible_host=34.226.206.37 ansible_user=ubuntu ansible_ssh_private_key_file=../final-project-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3